public class Constants {

	//Variable
    public static final String BATCH_FORECAST_STATUS = 'Batch Capture Forecast Variance Status';
    public static final Integer PAGE_SIZE = 100;
    public static final List<String> HEADER_LIST = new List<String>{'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Total'};
    public static final List<String> CMD_LINK_LIST = new List<String>{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z' ,'Other', 'All'};
	public static final Double CURRENT_YEAR_BUDGET_LIMIT = 250000;
    public static final Double CURRENT_YEAR_BUDGET_LIMIT_MIN = 100000;
}